### ISSUE TITLE
several questions

### ISSUE THREAD

**Issue by xtuyaowu** [yusuftaufiq/cmlabs-backend-crawler-freelance-test#1]
hi Yusuf
    thanks for you amaze work! 
    1、can you download .xls .pdf .doc Now download error:
         ERROR PlaywrightCrawler: Request failed and reached maximum retries. page.goto: net::ERR_ABORTED at

   2、Can you save the crawled url and the corresponding title into a csv?

**Comment by yusuftaufiq** [comment]
I'm not sure if I can fulfill your request. Actually, I built this repository for a job technical test a month ago and I don't plan to maintain this repository for a while as I'm currently busy with my work.

But feel free to fork this repository and modify it according to your needs, there are no license restrictions for this repository :)

**Comment by xtuyaowu** [comment]
got thanks！

**Comment by xtuyaowu** [comment]
thanks again！
